### ISSUE TITLE
Interest in using Chroma?

### ISSUE THREAD

**Issue by cameronelliott** [osteele/gojekyll#41]
I wonder if there has been any thought or discussions regarding using [Chroma](https://github.com/alecthomas/chroma) or another Go based code highligher?

Thanks

**Comment by osteele** [comment]
I would welcome this improvement.

**Comment by osteele** [comment]
Thank you for the suggestion. I'm re-opening it because I would still welcome the improvement if anyone wants to contribute it – I did not mean to imply that I expected @cameronelliott to write it.

 I will assign this to myself if I start on it myself.

**Comment by cameronelliott** [comment]
@osteele I am exploring different static generators, I was using gostatic for over a year or two, so I did experiment with adding Chroma into gostatic. You can see the work here, just in case it helps you. 
https://github.com/piranha/gostatic/pull/115

**Comment by cameronelliott** [comment]
Maybe I should not have closed! ??
