### ISSUE TITLE
when running go install gojekyll get error

### ISSUE THREAD

**Issue by MikeCongdon1** [osteele/gojekyll#46]
## Checklist

- [x] I have search the [issue list](https://github.com/osteele/gojekyll/issues) for my issue.
- [x ] I have verified the behavior with `jekyll`.  (N/A)
- [x] I tried hard to create a reproducible test case.

## System information
Rocky 8
(installing error)

## Expected behavior
`go install github.com/osteele/gojekyll@latest` will install & put a binary

## Actual behavior

doesn't install, fails with the following:
```
...
go: github.com/osteele/gojekyll imports
	github.com/osteele/gojekyll/commands imports
	gopkg.in/alecthomas/kingpin.v2: gopkg.in/alecthomas/kingpin.v2@v2.3.2: parsing go.mod:
	module declares its path as: github.com/alecthomas/kingpin/v2
	        but was required as: gopkg.in/alecthomas/kingpin.v2
```

## Steps to reproduce the behavior
Rocky 8,
Go 1.19.1
`go install l github.com/osteele/gojekyll@latest`

## Possible Solution
Fix go.mod file

**Comment by danog** [comment]
Fixed!
